-- Canvas RAG Integration - Vector Store and Search Function
-- Adds canvas_content_vectors table with pgvector support and semantic search function

-- =============================================
-- 1. Enable pgvector extension
-- =============================================
CREATE EXTENSION IF NOT EXISTS vector;

COMMENT ON EXTENSION vector IS 'Vector data type for storing embeddings';

-- =============================================
-- 2. Create canvas_content_vectors table
-- =============================================
CREATE TABLE IF NOT EXISTS public.canvas_content_vectors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  canvas_course_id uuid NOT NULL REFERENCES public.canvas_courses(id) ON DELETE CASCADE,
  canvas_item_id text NOT NULL,
  item_name text,
  item_type text,
  chunk_index integer DEFAULT 0,
  chunk_text text NOT NULL,
  embedding vector(1536), -- text-embedding-3-small dimensions
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.canvas_content_vectors IS 'Vector embeddings of Canvas course content for RAG-based AI features';
COMMENT ON COLUMN public.canvas_content_vectors.user_id IS 'User who owns the linked study set';
COMMENT ON COLUMN public.canvas_content_vectors.canvas_course_id IS 'Source Canvas course';
COMMENT ON COLUMN public.canvas_content_vectors.canvas_item_id IS 'Canvas item ID (file, page, assignment, etc.)';
COMMENT ON COLUMN public.canvas_content_vectors.item_name IS 'Display name of the Canvas item';
COMMENT ON COLUMN public.canvas_content_vectors.item_type IS 'Type of Canvas item (File, Page, Assignment, etc.)';
COMMENT ON COLUMN public.canvas_content_vectors.chunk_index IS 'Index of this chunk within the item';
COMMENT ON COLUMN public.canvas_content_vectors.chunk_text IS 'Text content of this chunk';
COMMENT ON COLUMN public.canvas_content_vectors.embedding IS 'Vector embedding generated by text-embedding-3-small';
COMMENT ON COLUMN public.canvas_content_vectors.metadata IS 'Additional metadata from vectorization (line numbers, loc, source, etc.)';

-- =============================================
-- 3. Create indexes for performance
-- =============================================
CREATE INDEX IF NOT EXISTS idx_canvas_vectors_course_id ON public.canvas_content_vectors(canvas_course_id);
COMMENT ON INDEX idx_canvas_vectors_course_id IS 'Fast lookup of vectors by Canvas course';

CREATE INDEX IF NOT EXISTS idx_canvas_vectors_user_id ON public.canvas_content_vectors(user_id);
COMMENT ON INDEX idx_canvas_vectors_user_id IS 'Fast lookup of vectors by user';

CREATE INDEX IF NOT EXISTS idx_canvas_vectors_item_id ON public.canvas_content_vectors(canvas_item_id);
COMMENT ON INDEX idx_canvas_vectors_item_id IS 'Fast lookup of vectors by Canvas item';

-- IVFFlat index for cosine similarity search (optimal for embeddings)
CREATE INDEX IF NOT EXISTS idx_canvas_vectors_embedding
  ON public.canvas_content_vectors
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);
COMMENT ON INDEX idx_canvas_vectors_embedding IS 'IVFFlat index for fast vector similarity search using cosine distance';

-- =============================================
-- 4. Enable Row Level Security
-- =============================================
ALTER TABLE public.canvas_content_vectors ENABLE ROW LEVEL SECURITY;

-- =============================================
-- 5. Create RLS Policies
-- =============================================
-- Policy 1: Users can SELECT their own vectors
CREATE POLICY "Users can view their own canvas vectors"
  ON public.canvas_content_vectors FOR SELECT
  USING (user_id = auth.uid());

COMMENT ON POLICY "Users can view their own canvas vectors" ON public.canvas_content_vectors
  IS 'Users can only view vector embeddings they own';

-- Policy 2: Users can INSERT their own vectors
CREATE POLICY "Users can insert their own canvas vectors"
  ON public.canvas_content_vectors FOR INSERT
  WITH CHECK (user_id = auth.uid());

COMMENT ON POLICY "Users can insert their own canvas vectors" ON public.canvas_content_vectors
  IS 'Users can only insert vectors for their own study sets';

-- Policy 3: Service role can RPC call the search function (bypasses RLS)
-- (This is automatically allowed since functions called with service role bypass RLS)

-- =============================================
-- 6. Create search_canvas_vectors function
-- =============================================
CREATE OR REPLACE FUNCTION public.search_canvas_vectors(
  query_embedding vector(1536),
  course_ids uuid[],
  user_id_param uuid,
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  id uuid,
  canvas_item_id text,
  item_name text,
  item_type text,
  chunk_text text,
  similarity float,
  metadata jsonb
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    cv.id,
    cv.canvas_item_id,
    cv.item_name,
    cv.item_type,
    cv.chunk_text,
    ROUND((1 - (cv.embedding <=> query_embedding))::numeric, 4)::float AS similarity,
    cv.metadata
  FROM public.canvas_content_vectors cv
  WHERE
    cv.user_id = user_id_param
    AND cv.canvas_course_id = ANY(course_ids)
    AND 1 - (cv.embedding <=> query_embedding) > match_threshold
  ORDER BY cv.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION public.search_canvas_vectors(vector, uuid[], uuid, float, int) IS
  'Search for semantically similar canvas content using cosine distance. Returns top N results above similarity threshold.';

-- =============================================
-- 7. Create trigger for updated_at
-- =============================================
CREATE TRIGGER update_canvas_content_vectors_updated_at
  BEFORE UPDATE ON public.canvas_content_vectors
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

COMMENT ON TRIGGER update_canvas_content_vectors_updated_at ON public.canvas_content_vectors
  IS 'Auto-update updated_at timestamp on record modification';
